version: "3"

services:
  gin:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: api-gin
    volumes:
      - ./api/src:/go/src/
    ports:
      - 8080:8080
    tty: true
    command: "/bin/sh"
