version: "3"

services:
  gin:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: api-gin
    volumes:
      - ./api/src:/go/src/github.com/Ko1103/docker-gin-go
    ports:
      - 8080:8080
    tty: true
    command: "/bin/sh"
